version: '3'

services:
  app:
    build: .
    command: npm start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    links:
      - "mongo:mongo"
  mongo:
    image: mongo:latest
  