version: '3'

services:
  app:
    build: .
    restart: always
    command: npm start
    volumes:
      - .:/app/
      - /app/node_modules
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    links:
      - "mongo:mongo"
  mongo:
    image: mongo:latest
    volumes:
      - /db:/data/db
    ports:
      - "27017:27017"
