version: '3'

services:
  arudb:
    image: mongo:latest
    container_name: aru-db
    restart: always
  aru:
    container_name: aru-discord
    restart: always
    build: .
    environment:
      - MONGO_URL=${MONGO_URL}
      - PREFIX=${PREFIX}
      - TIME_FORMAT=${TIME_FORMAT}
      - GAME_NAME=${GAME_NAME}
      - STREAM_URL=${STREAM_URL}
      - DISCORD_PW_KEY=${DISCORD_PW_KEY}
      - CARBONITEX_KEY=${CARBONITEX_KEY}
      - DISCORDBOTS_KEY=${DISCORDBOTS_KEY}
      - TMDB_KEY=${TMDB_KEY}
      - SENTRY_URL=${SENTRY_URL}
      - DISCORD_TOKEN=${DISCORD_TOKEN}
    ports:
      - ${API_PORT}:${API_PORT}
    depends_on:
      - arudb
    links:
      - "arudb:arudb"
